### ISSUE TITLE
0.3 won't start

### ISSUE THREAD

**Issue by Noctis-** [4rtzel/poe-archnemesis-scanner#13]
0.2 worked for me ... 0.3 (installer, not manual), will just start and close.

can't find logs anywhere ...

🤷

**Comment by tonpix** [comment]
Happened to me too - 0.2 worked, 0.3 just flashes a command line window

**Comment by 4rtzel** [comment]
Do you have any antivirus running? In 0.0.3 I started using some winapi functions to scan the windows. Maybe it triggers the antivirus?

**Comment by Noctis-** [comment]
Nope ... whatever win 11 uses by default ... windows defender ? 
oh ... since we're doing this ... win 11 , 2 screens, high res (3440x1440), GTX 2070
Let me know if you need anything else, i'm happy to help

**Comment by 4rtzel** [comment]
Windows 11 is still unknown variable to me..

Could you try launching it from the powershell? It should preserve the logs and show you the errors.

**Comment by Noctis-** [comment]
do i need to get python, or just run the commands from the power shell in the directory ?

**Comment by 4rtzel** [comment]
Just run it from the directory like that:
```
.\poe_arch_scanner.exe
```

**Comment by Noctis-** [comment]
```PS D:\Games\Path of Exile - Helpers\poe_arch_scanner 0.3> .\poe_arch_scanner.exe
Traceback (most recent call last):
  File "poe_arch_scanner.py", line 603, in <module>
  File "poe_arch_scanner.py", line 574, in get_poe_window_info
pywintypes.error: (1400, 'GetWindowRect', 'Invalid window handle.')
[10784] Failed to execute script 'poe_arch_scanner' due to unhandled exception!
PS D:\Games\Path of Exile - Helpers\poe_arch_scanner 0.3>```

**Comment by Noctis-** [comment]
happy to hop on discord if that helps you

**Comment by tonpix** [comment]
I'm using Windows 10, no 3rd party antivirus installed. Using 2 monitors, 1920x1080 144hz (this one is for POE) and secondary 1920x1200 60hz.

`Traceback (most recent call last):
  File "poe_arch_scanner.py", line 603, in <module>
  File "poe_arch_scanner.py", line 574, in get_poe_window_info
pywintypes.error: (1400, 'GetWindowRect', 'Invalid window handle.')
[14208] Failed to execute script 'poe_arch_scanner' due to unhandled exception!`

**Comment by 4rtzel** [comment]
Is your poe game running?

**Comment by tonpix** [comment]
It wasn't, I tried to launch tool before POE. Now, with game running, your tool seems to be launching and working pretty well (so far I've had to drop threshold from 0.94 o 0.9 and and noticed there are minimized Setting popups I can't close, I'm seeing 'clones' on taskbar - can't close those with right click -> Close).

Thanks!

**Comment by 4rtzel** [comment]
In 0.0.3 program tries to detect your poe window to get its resolution and position. It's necessary to support "Windowed" mode. I think I should add a notification that the game is not running and fallback to the default parameters if so.

Oh, I noticed it too. It happens if you click 'Settings' multiple times before closing the window. You can restart the program to fix that.

**Comment by Noctis-** [comment]
yep ...wasn't running ... 0.2 ran without it running ... i'll give it a spin in 10 or so 👍

**Comment by Noctis-** [comment]
Yep ... can confirm it's happily working if you have POE open 👍  legend.
I think you're missing a recipee though ..i'll open another issue

Also, you might want to use these defaults for 3440*1440 : 145,420,600,610 (probably 610 or 600 for both in the 2 last ones ... but yeah ... that works for me)
